### ISSUE TITLE
setAutoFilter over writes when used repeatedly in same sheet

### ISSUE THREAD

**Issue by matwec** [miraisolutions/xlconnect-java#12]
When writing data to a new file, if setAutoFilter is used repeatedly for different data regions in the same sheet, only the last request in order will have effect. Earlier filters will be removed within the sheet.

```
sTable <- data.frame(replicate(4,sample(0:1,7,rep=TRUE)))
tTable <- data.frame(replicate(4,sample(0:1,7,rep=TRUE)))
wb <- loadWorkbook('filename2.xlsx', create=TRUE)
createSheet(wb, name = 'Summary')
writeWorksheet(wb, tTable, sheet = 'Summary', startRow = 1, startCol = 1, header = TRUE)
setAutoFilter(wb, 'Summary', aref('A1', dim(tTable)))
writeWorksheet(wb, sTable, sheet = 'Summary', startRow = 10, startCol = 1, header = TRUE)
setAutoFilter(wb, 'Summary', aref('A10', dim(sTable)))
saveWorkbook(wb)
```
![error](https://user-images.githubusercontent.com/83701322/143425500-f5f4c770-9d50-4373-8a3e-d83ce1f49e32.PNG)

I have tried to analyze the intended behavior but was not able to get past the calls to the Sheet method. The documentation does not say.

**Comment by riccardoporreca** [comment]
@matwec, only a single AutoFilter is supported per sheet, hence the behavior you describe is totally expected.

This isn't anything surprising: it is the same behavior you would get using e.g. Excel / LibreOfficeCalc if you manually try to AutoFilter a first data region and then a second one.
